name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
      run: bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
    - name: Keep Running Ubuntu System and keepAlive
      run: sleep 6h
